# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
